baseURL = "https://sand.libert.xyz" # Hostname (and path) to the root.
title = "libert.xyz" # Site title.
theme = "coder-custom" # Set the theme.
languagecode = "en" # The site’s language code.
enableEmoji = true


canonifyurls = true # Enable to turn relative URLs into absolute.

#pygmentsstyle = "friendly" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[pagination]
pagerSize = 6

[params] # theme parameters
    author = "Libert (lih-BERT)" # Author's name.
    info = "DevOps Culture / Cloud Computing / Coffee Enthusiast" # Author's job title or info.
    description = "libert personal website" # Site description.
    keywords = "blog,devops,libert,aws,python,linux,bash" # Site keywords.

    ##avatarurl = "images/avatar.jpg"
    #footercontent = "Enter a text here."
    dateformat = "January 2, 2006"

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
	  custom_css = []
    rtl = false
    math = true

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false


    #Content-Security-Policy section
    [params.csp]
    childsrc = ["'self'"]
    fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
    formaction = ["'self'"]
    framesrc = ["'self'", "https://www.youtube.com"]
    imgsrc = ["'self'"]
    objectsrc = ["'none'"]
    stylesrc = [
      "'self'",
       "'unsafe-inline'",
       "https://fonts.googleapis.com/",
       "https://cdn.jsdelivr.net/",
     ]
    scriptsrc = [
       "'self'",
       "'unsafe-inline'",
       "https://www.google-analytics.com",
       "https://cdn.jsdelivr.net/",
     ]
    prefetchsrc = ["'self'"]
    # # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
    connectsrc = ["'self'", "https://www.google-analytics.com"]


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/libert-xyz"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/rschmidtz"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"

[[menu.main]]
    name = "Open Source Projects"
    weight = 2
    url = "/open-source/"

#[[menu.main]]
#    name = "#HashTags"
#    weight = 2
#    url = "/tags/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
